### PR TITLE
Fix: issue with cmd + s on status-page/new form

### LINKED ISSUE #914: When saving  monitor, using the keyboard shortcut Cmd + S it should run the checks
### Reproduction / Replay Link (Optional)

_No response_

### Description

API is a reserved slug, so you cannot use it for your status page. However, if you save your status page using the keyboard shortcut Cmd + S, you can still save the page with that slug.

### Environment

_No response_

### PR DESCRIPTION
**Pull request by Ipriyankrajai**
## Type of change

- [x] 🐛 Bug fix

## Description
Moved checkUniqueSlug funtion to onSubmit  function.

Fixes #914 

### Before this PR
There was no validation for api on status page when you  use cmd + s to save

### After this PR
It will check for validation even if you use cmd + s to save

### CODE REVIEW

File: apps/web/src/components/forms/status-page/form.tsx [hunk 1]
```diff
@@ -115,35 +115,41 @@ export function StatusPageForm({
...
-        } else {
-          const page = await api.page.create.mutate(props);
-          const id = page?.id || null;
-          router.replace(`?${updateSearchParams({ id })}`); // to stay on same page and enable 'Advanced' tab
-        }
+    const isUnique = await checkUniqueSlug();
+    if (!isUnique) {
+      // the user will already have the "error" message - we include a toast as well
+      toastAction("unique-slug");
+    } else {
```
Comment (mxkaske) [inline apps/web/src/components/forms/status-page/form.tsx]: Thanks @Ipriyankrajai! One thing: can we move the async call within the `startTransition` so that the pending state gets fired immediately?

**Review by mxkaske — APPROVED** [review]
Thanks @Ipriyankrajai!

File: apps/web/src/components/forms/status-page/form.tsx (hunk 1 above)
Comment (Ipriyankrajai) [reply apps/web/src/components/forms/status-page/form.tsx]: Sure! I was thinking that only

**Comment by thibaultleouay** [comment]
Thanks again  @Ipriyankrajai
