### PR TITLE
fix: only regenerate slug if there is no default

### LINKED ISSUE #231: bug: auto-generate slug
With #198 we have introduced a bug and temporarily disabled the functionality for now.

The reason: If your slug was different to what would have been generated, whenever you would re-edit a page, it would `slugify` the title on every form opening.

How to reproduce:

1. uncomment the lines here:
https://github.com/openstatusHQ/openstatus/blob/7a80fbdd643174f20e2d90c3bc3d63422652b646/apps/web/src/components/forms/status-page-form.tsx#L95
2. create a status page (edited) with a `title` and change the `slug` that has been auto generated - and save
3. edit the same status page (edited) - the `slug` should have been updated to the auto generated one, not the one saved

### PR DESCRIPTION
**Pull request by AmoabaKelvin**
Fixes #231

### CODE REVIEW

File: apps/web/src/components/forms/status-page-form.tsx [hunk 1]
```diff
@@ -92,12 +93,11 @@ export function StatusPageForm({
...
-  // useEffect(() => {
-  //   if (!watchSlug) {
-  //     form.setValue("slug", slugify(watchTitle));
-  //   }
-  // }, [watchTitle, form, watchSlug]);
+  useEffect(() => {
+    if (!watchSlug) {
+      form.setValue("slug", slugify(watchTitle));
+    }
+  }, [watchTitle, form, watchSlug]);
```
Comment (mxkaske) [inline apps/web/src/components/forms/status-page-form.tsx]: Thanks for tackling that issue! 🚀

This will trigger the `.setValue` function only if the `slug` is undefined or an empty string in our case. If the user deletes the entire slugified content, the function will get fired and automatically resets the `slug` from `undefined` to the slugified content.

I think we should track if the `defaultValue.slug` exists. Only if not, we watch the changes from the `title` input to update the `slug` input. Changing the `slug` afterwards is possible as the `useEffect` will not get fired. Only if, on creation (as `defaultValues` is undefined)m the `title` is changed again after having updated the auto-generated `slug`, it will re-change the already updated `slug`. (Getting inception vibes here.)

Let me know if that works!

```suggestion
  useEffect(() => {
    if (!defaultValues?.title) {
      form.setValue("slug", slugify(watchTitle));
    }
  }, [watchTitle, form, defaultValues]);
```

File: apps/web/src/components/forms/status-page-form.tsx [hunk 2]
```diff
@@ -92,12 +93,11 @@ export function StatusPageForm({
...
-  // useEffect(() => {
-  //   if (!watchSlug) {
-  //     form.setValue("slug", slugify(watchTitle));
-  //   }
-  // }, [watchTitle, form, watchSlug]);
+  useEffect(() => {
+    if (!defaultValues?.title) {
+      form.setValue("slug", slugify(watchTitle));
+    }
+  }, [watchTitle, form, watchSlug, defaultValues?.title]);
```
Comment (mxkaske) [inline apps/web/src/components/forms/status-page-form.tsx]: You'll need to remove `watchSlug` from deps, otherwise we won't be able to customize the slug on page creation. Otherwise, lgtm!

```suggestion
  }, [watchTitle, form, defaultValues?.title]);
```

**Comment by mxkaske** [comment]
Thanks Kelvin! 🔥
