### PR TITLE
fix: Only show body input when method is POST

### LINKED ISSUE #232: [OPE-86] Only show `body` Input when advanced monitor settings method is "POST"
The `body` textarea should be `hidden` if "GET" is chosen. Otherwise, if a user is selecting the "GET" method and adds a body, we will get:

```
[TypeError: Request with GET/HEAD method cannot have body.]
```

<sub>From [SyncLinear.com](https://synclinear.com) | [OPE-86](https://linear.app/openstatus/issue/OPE-86/only-show-body-input-when-advanced-monitor-settings-method-is-post)</sub>

### PR DESCRIPTION
**Pull request by zahid47**
fixes #232

### CODE REVIEW

File: apps/web/src/components/forms/advanced-monitor-form.tsx [hunk 1]
```diff
@@ -178,9 +185,10 @@ export function AdvancedMonitorForm({ defaultValues, workspaceSlug }: Props) {
             <FormItem className="sm:col-span-2 sm:col-start-1 sm:self-baseline">
               <FormLabel>Method</FormLabel>
               <Select
-                onValueChange={(value) =>
-                  field.onChange(methodsEnum.parse(value))
-                }
+                onValueChange={(value) => {
+                  field.onChange(methodsEnum.parse(value));
+                  form.resetField("body");
```
Comment (mxkaske) [inline apps/web/src/components/forms/advanced-monitor-form.tsx]: We will need an additional config here, otherwise it will be back to `defaultValue.body`, which might be defined if we switch from "POST" back to "GET". (see [docs](https://react-hook-form.com/docs/useform/resetfield)).
```suggestion
                  form.resetField("body", { defaultValue: "" });
```

**Review by mxkaske — COMMENTED** [review]
besides the one comment, lgtm!

File: apps/web/src/components/forms/advanced-monitor-form.tsx (hunk 1 above)
Comment (zahid47) [reply apps/web/src/components/forms/advanced-monitor-form.tsx]: Yep, I totally missed that case. Will push another commit.

File: apps/web/src/components/forms/advanced-monitor-form.tsx [hunk 2]
```diff
@@ -65,6 +71,7 @@ export function AdvancedMonitorForm({ defaultValues, workspaceSlug }: Props) {
       method: defaultValues?.method ?? "GET",
     },
   });
+  const methodWatch = form.watch("method");
```
Comment (mxkaske) [inline apps/web/src/components/forms/advanced-monitor-form.tsx]: Good thing on the rename! I'd suggest to go for `watchMethod` as this is our current naming convention.

**Comment by mxkaske** [comment]
Thanks @zahid47! 🚀

**Review by mxkaske — APPROVED** [review]
